version: '3.9'
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"

  migrations:
    image: kukymbr/goose-docker:3.24.1
    depends_on:
      - db
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=db port=5432 user=postgres password=postgres dbname=dbname
    volumes:
      - ./migrations:/migrations

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"